spring.application.name=taskapp


# config to connect the project to posgresql database

#tells the application to use the postgresql driver
spring.datasource.driver-class-name=org.postgresql.Driver

#where to find the postgresql database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

#username
spring.datasource.username=postgres

#password
spring.datasource.password=changemeinprod!

#automatically set up and update the db schema to match the jpa entities that we will create in our project
spring.jpa.hibernate.ddl-auto=update